# Generated by Django 3.0.7 on 2020-06-10 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id', '-timestamp']},
        ),
    ]
