# Generated by Django 3.0.7 on 2020-06-10 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcoApp', '0002_auto_20200610_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
