# Generated by Django 3.0.7 on 2020-06-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoApp', '0003_auto_20200610_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(default='Описание')),
                ('keywords', models.CharField(default='Ключевые слова', max_length=120)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('content', models.TextField(default='Контент')),
                ('visible', models.BooleanField(default=1)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
