# Generated by Django 3.0.7 on 2020-06-11 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcoApp', '0004_promotions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Promotions',
            new_name='Promotion',
        ),
    ]
