# Generated by Django 3.0.7 on 2020-06-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoApp', '0006_promotion_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
